Port axum 0.2 upgrade to 0.11.x branch
djc/askama pull request #740
Opened 2022-11-07 10:28 UTC by djc

Fixes #738.

2022-11-07 15:53 UTC, Kijewski requested changes
Please rebase. Except for the one comment it looks good to me.

I love the simplification, thank you @jplatte!

2022-11-07 15:53 UTC, Kijewski commented on askama_shared/src/generator.rs
> +             -> ::askama_axum::Response {",
The linebreak can be omitted.

2022-11-15 09:58 UTC, djc commented
Not sure what you meant by rebase? This intentionally targets the 0.11.x branch.

2022-11-25 23:52 UTC, dnaka91 commented
Axum just released a new version, should this be bumped to the now new `axum-core` v`0.3.0` instead?

2022-11-25 23:54 UTC, djc commented
Let's merge this as is and then someone can follow up with a 0.3 PR.

2022-11-25 23:58 UTC, Kijewski approved these changes
LGTM

2022-11-25 23:59 UTC, merged

2022-11-26 01:21 UTC, dnaka91 commented
Seems a bump to 0.3 is already happening in #716 🎉