parser: limit target recursion
djc/askama pull request #942
Opened 2024-01-10 10:23 UTC by djc

#911 introduced support for multiple targets, but I missed the need to limit recursion (see #866), which triggered a bunch of issues from OSS Fuzz.

2024-01-10 10:28 UTC, GuillaumeGomez requested changes
Changes look good but please add a regression test to ensure it does indeed fail compilation as expected.

2024-01-11 12:56 UTC, djc commented
Added a test case.

2024-01-11 13:28 UTC, Kijewski approved these changes

2024-01-11 14:16 UTC, GuillaumeGomez approved these changes
All good for me, thanks!

2024-01-11 15:32 UTC, merged