Remove optional Options argument from built-in markdown filter
djc/askama pull request #998
Opened 2024-04-01 11:38 UTC by djc

comrak does relatively many semver-incompatible releases, and because we expose direct access to `comrak::Options` via the `markdown` filter that makes Askama semver-incompatible. Since I doubt a lot of people depend on this and it can easily a custom filter, I'd prefer to just remove the semver hazard here.

2024-04-01 14:54 UTC, GuillaumeGomez approved these changes

2024-04-02 20:17 UTC, Kijewski commented on askama_derive/src/generator.rs
> +            _ => return Err("markdown filter expects one argument".into()),
I'd say "no argument", because the input is an implicit argument.

2024-04-02 20:19 UTC, Kijewski requested changes
Yes, it makes sense to keep the built-in filters simple.

The last paragraph of <https://github.com/djc/askama/blob/main/book/src/filters.md#markdown> needs to be updated.

2024-04-06 21:13 UTC, Kijewski commented
We removed the markdown filter in #1003, so this PR is obsolete.

2024-04-06 21:13 UTC, closed without merging